"""Criação do banco com campos opcionais

Revision ID: ef67acdbcdca
Revises: 
Create Date: 2026-06-18 00:32:00.865888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef67acdbcdca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dados_funcionais',
    sa.Column('masp', sa.Integer(), nullable=False),
    sa.Column('num_admissao', sa.Integer(), nullable=False),
    sa.Column('nome_servidor', sa.String(length=150), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('data_inicio_exercicio', sa.Date(), nullable=True),
    sa.Column('cod_idade', sa.Integer(), nullable=True),
    sa.Column('cod_sexo', sa.String(length=10), nullable=True),
    sa.Column('cod_carreira', sa.String(length=50), nullable=True),
    sa.Column('situacao_funcional', sa.String(length=100), nullable=True),
    sa.Column('situacao_servidor', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('masp', 'num_admissao')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('dados_funcionais')
    # ### end Alembic commands ###
